[KFI] Zip file always unpacked.
SenseNet/sn-admin pull request #18
Opened 2018-01-19 01:37 UTC by kavics

Please review and merge.

2018-01-19 01:52 UTC, kavics commented
Manual test cases are successfully executed.

"pkg": a directory that contains manifest.xml with a Trace command: "overridden message"
"pkg.zip": compressed package with a Trace command: "original message"

Worklog:
```
	before		after		SnAdmin
Case	pkg.zip	pkg	pkg.zip	pkg	command		Expected message		Result
===============================================================================================
1	-	-	-	-	pkg		Given package does not exist	ok
2	-	-	-	-	pkg.zip		Given package does not exist	ok
3	-	exists	-	exists	pkg		overridden message		ok
4	-	exists	-	exists	pkg.zip		Given package does not exist	ok
5	exists	-	exists	exists	pkg		original message		ok
6	exists	-	exists	exists	pkg.zip		original message		ok
7	exists	exists	exists	exists	pkg		original message		ok
8	exists	exists	exists	exists	pkg.zip		original message		ok
```

2018-01-30 14:41 UTC, tusmester requested changes

2018-01-30 14:41 UTC, tusmester commented on src/SnAdmin/SnAdmin.cs
> +                string workerExe;
Why is this needed?

2018-01-30 14:41 UTC, tusmester commented on src/SnAdminTests/ExecutionTests.cs
> +            //var consoleText = console.GetStringBuilder().ToString();
Remove or rewrite pls.

2018-01-30 14:41 UTC, tusmester commented on src/SnAdminTests/ExecutionTests.cs
> +            //var consoleText = console.GetStringBuilder().ToString();
Remove or rewrite pls.

2018-02-05 12:59 UTC, tusmester approved these changes

2018-02-05 12:59 UTC, merged